platform:
  - x64

image: Visual Studio 2017
  
configuration:
#  - Release
  - Debug

environment:
  matrix:
    - USE_CONTEXT: ON      
      USE_EMBEDTLS: OFF

#    - USE_CONTEXT: OFF
#      USE_EMBEDTLS: OFF

#    - USE_CONTEXT: OFF
#      USE_EMBEDTLS: ON


matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

before_build:
  - cmake --version
  - cmake   -G "Visual Studio 15 2017 Win64" -Dfatal_warnings=OFF -Dcoveralls=OFF . && exit 0

build_script:
  - msbuild cn-cbor.sln
  - dir dist\lib\Debug
  - ctest -C %CONFIGURATION%
